create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "paid_at" timestamp with time zone default now(),
    "uid" uuid,
    "price" numeric,
    "merchant" text,
    "currency" text,
    "refId" text,
    "transId" text,
    "status" text,
    "method" text,
    "vs" text,
    "service_type" text
);


alter table "public"."payments" enable row level security;

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."payments" add constraint "payments_uid_fkey" FOREIGN KEY (uid) REFERENCES auth.users(id) not valid;

alter table "public"."payments" validate constraint "payments_uid_fkey";


