create table "public"."app" (
    "id" bigint generated by default as identity not null,
    "version" text
);


alter table "public"."app" enable row level security;

CREATE UNIQUE INDEX app_pkey ON public.app USING btree (id);

alter table "public"."app" add constraint "app_pkey" PRIMARY KEY using index "app_pkey";

create policy "Enable read access for all users"
on "public"."app"
as permissive
for select
to public
using (true);



