drop policy "Enable delete for users based on user_id" on "public"."payment_log";

create table "public"."invoice" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "uid" uuid,
    "firstname" text,
    "lastname" text,
    "email" text,
    "phone" text,
    "is_company" boolean default false,
    "company_name" text,
    "ic" text,
    "dic" text,
    "fakturoid_subject_id" numeric
);


alter table "public"."invoice" enable row level security;

alter table "public"."payment_log" add column "fakturoid_invoice_id" text;

CREATE UNIQUE INDEX invoice_pkey ON public.invoice USING btree (id);

alter table "public"."invoice" add constraint "invoice_pkey" PRIMARY KEY using index "invoice_pkey";

alter table "public"."invoice" add constraint "invoice_uid_fkey" FOREIGN KEY (uid) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."invoice" validate constraint "invoice_uid_fkey";

create policy "Enable select for users based on user_id"
on "public"."payment_log"
as permissive
for select
to public
using ((auth.uid() = uid));


create policy "Enable read access for all users"
on "public"."purchase_type"
as permissive
for select
to public
using (true);



