name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version here, adjust as necessary

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build
        # This command should compile your TypeScript and any other sources, and output to /dist or another folder

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist # This should match the output directory of your build command

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1